### ISSUE TITLE
Version mismatch error when loading gta5.hk plugin

### ISSUE THREAD

**Issue by JiamingSuen** [philkr/gamehook_gtav#1]
Hi philkr, thanks for this amazing work.
I'm trying to reproduce the optical flow capturing inside GTA as you presented in the paper. After compiling the two projects(`gamehook` and `gamehook_gtav`) I put `dxgi.dll` and `gta5.hk` in the GTA directory as you suggested. The hooking process seems fine but ScriptHookV reported a fatal error:
![image](https://user-images.githubusercontent.com/8616975/42278032-02d13386-7fcc-11e8-86d7-7515bb6e8ea3.png)

As shown in the screenshot, my game version(bottom right) is supported by this version of ScriptHookV. I tried to start the game with `ScriptHookV.dll` only and with both `ScriptHookV.dll` and `dxgi.dll`, the game started as usual and according to the intercept log the hooking process is also working well. 

Am I doing anything wrong? I tried digging up in the code for a while and didn't see what would affect version detection of ScriptHook.

Thanks for your time.

**Comment by el3ment** [comment]
I am having the same error - did you figure this out @JiamingSuen ?

**Comment by philkr** [comment]
maybe we can narrow this down a bit.
First of all I used `1.0.11080.2` for all the capture and to develop this code. Does scripthook work without gamehook (using `dinput8.dll` without `dxgi.dll`)? If yes, does the game start once you rename (or delete `dinput8.dll`) and put `dxgi.dll` of gamehook into the directory?

**Comment by el3ment** [comment]
With `dinput8.dll` and `scripthookv.dll` in the folder, and no `dxgi.dll` (gamehook.dll) it loads fine and produces an asiloader.log file with no errors (although it doesn't produce a scripthook log file but I'm not sure it's supposed to). 

When `dxgi.dll` is present without any *.hk files, it also loads fine. 

When any *.hk files (capture, python, gta5, server) are also in the directory, loading any of the plugins causes the error seen in @JiamingSuen's original post above.

**Comment by JiamingSuen** [comment]
I observe the same behavior as @el3ment stated. Loading with `scripthookv.dll` and `dinput8.dll` works fine and the Native Trainer is functioning normally. This error only occurs when any `.hk` plugins presented.

**Comment by el3ment** [comment]
After some playing around, it looks like the SDK files might be out of date. Updating the enums in main.h:113 so that `VER_1_0_1365_1_STEAM` is there seemed to allow it to run -- I have no idea what other issues this is going to cause. But I thought I would point it out. @philkr does your main.h file have `VER_1_0_1180_2_STEAM` and/or `VER_1_0_1180_2_NOSTEAM` listed?

**Comment by el3ment** [comment]
I take that back, it looks like that change allows all of the other HK files to load - but gta5.hk still has problems.

**Comment by el3ment** [comment]
gtastate.cpp:82 is where the issue happens. ~~What is really (really) confusing is that scriptRegister is used by pyhookv.cpp and gta5 project is using the exact same lib and header files.~~ Upon further review, the pyhookv.cpp file isn't part of a plugin file (*.hk) that is being loaded. "python.hk" doesn't use scriptRegister.

**Comment by el3ment** [comment]
Ok -  the issue was happening because GTA5Launcher.exe does not meet the criteria for ScriptHookV's check on version number. Adding a check in [api.cpp:125](https://github.com/philkr/gamehook/blob/master/wrapper/api.cpp#L125) in the gamehook repo so that plugins are not loaded will fix the problem. Something like:

```
WCHAR result[MAX_PATH] = {};
GetModuleFileNameW(static_cast<HMODULE>(nullptr), result, MAX_PATH);
HMODULE r = nullptr;
if (wcsstr(result, L"Launcher") == 0) {
	// Load the temp library
	r = LoadLibrary(temp_filename);
	if (!r) {
		LOG(WARN) << "LoadLibrary failed " << std::hex << GetLastError();
	}
}
```

**Comment by yulong314** [comment]
It doesn't work

**Comment by yulong314** [comment]
it worked when I change steam to "offline" mode

**Comment by philkr** [comment]
I just wanted to follow up on this. Did you figure out what the problem is exactly? Does @el3ment 's fix solve the problem? If yes, would you mind creating a PR?

**Comment by yulong314** [comment]
yes,   @el3ment 's fix works! only that there is two intercept log window now: one for game , another for launcher.
![bug](https://user-images.githubusercontent.com/19659558/42858252-279f0f80-8a80-11e8-81cd-3af263baf55c.jpg)

**Comment by yulong314** [comment]
And It still doesn't work if "NativeTrainer.asi" is in the gta5 directory.

**Comment by philkr** [comment]
https://github.com/philkr/gamehook/commit/22a0638540d31e6daf6b25278e222bdbabc5a86c should fix this issue. Please reopen if not.
