### ISSUE TITLE
Not hooking DrawInstancedIndirect

### ISSUE THREAD

**Issue by benjamintanweihao** [philkr/gamehook_gtav#9]
I managed to get everything set up, but I'm getting mostly 'Not hooking DrawInstancedIndirect' printed in the intercept log. Consequently, when I go to `http://localhost:8766/bmp?t=flow`, all I see is a black screen.

I also get 

```
[ 14:59:14 ] Target 'final' exists, but was not written. Check your plugins to make sure all targets are written properly!
[ 14:59:14 ] Target 'albedo' exists, but was not written. Check your plugins to make sure all targets are written properly!
```

Am I missing something?

**Comment by philkr** [comment]
ignore the not hooking message. The outputs not being produced is odd. I usually only get this message when the game is loading, once it's running you should see final and albedo. What game version are you using?
